- handlers/backend_handler.go
These were relying on matching specific error strings set by the `net/http` package.  This is a brittle approach, and there are better approaches, as the errors in question implement the `net.Error` interface.
This PR also removes specific handling for invalid content-length errors.  This hasn't worked since we upgraded to Go 1.2.
See individual commit messages for more details.
> Tidy up handling of backend HTTP errors.

- integration_tests/reload_api_test.go
- router_api.go
To help with debugging memory usage.
This could be useful, but It's worth noting that the `ReadMemoryStats()` call has to stop the world[1] in order to gather the stats, which could have a performance impact if it's hit rapidly.
[1] http://golang.org/src/runtime/mem.go?s=2417:2447#L63
> Add /memory-stats endpoint to the API.

- integration_tests/gone_test.go
- router.go
This makes is more consistent with the 404 handler, and helps see what's
going on when running in development.  In production these responses
will still be intercepted downstream and replaced with the proper error
page.
This also updates the router to use the same handler for all gone routes, which is a little more efficient.
> Add plain text response to goneHandler.

- Makefile
Currently, if gom install errors or is aborted, the _vendor directory
will still get its timestamp updated. This means that future make runs
won't attempt to re-run gom install.
This changes the _vendor make target to use a stamp file to avoid this
issue.  It also combines the task for the project importpath into the
main task to avoid needlessly rerunning gom install every time the
to-level directory's timestamp is updated.
> Fix Makefile race condition

- integration_tests/backend_selection_test.go
- integration_tests/error_handling_test.go
- triemux/mux.go
If the connection to Mongodb fails when the router first starts up, it
will come up with an empty routing table.  Previously this would return
a 404 for all requests.  These would be served to end users and cached
upstream.
Running with an empty routing table is always going to be erroneous, so
this changes it to return a 503's in this situation. This will cause
upstream caches to serve from stale, and additionally won't be cached
anywhere.
> Return a 503 when running with no routes.

- Makefile
- jenkins.sh
- main.go
- version.go
This will allow us to determine what version of the router a given
binary is, and additionally, which version of Go was used to compile it.
> Add version information to help output. 

- handlers/redirect_handler.go
- integration_tests/redirect_test.go
The current cache TTL of 1 day can cause problems when redirects are
changed, or even replaced with a regular route.
Reducing this to 30 minutes will make it less surprising (it's more
consistent with the rest of the stack). It shouldn't make much
difference to the load on the servers because redirects are very
cheap to serve.
> Reduce redirect cache TTL to 30 mins.

- handlers/backend_handler.go
- integration_tests/backend_helpers.go
- integration_tests/proxy_function_test.go
- main.go
Add a test to verify that the router can connect to a HTTPS backend.
For this, add the `ROUTER_TLS_SKIP_VERIFY` environment variable, which
will cause the router to skip verification of backend TLS certificates
when set to a non-empty value.
This option is only intended for use by the tests. We were hesitant to
do this given that disabling TLS verification adjusts the normal
application behaviour, however we decided this is an acceptable
compromise given that we're testing the TLS transport, not the
verification of TLS certificates (though we may later decide to test for
that separately).
Log a warning when `ROUTER_TLS_SKIP_VERIFY` is enabled to make it clear
that it is not intended for production use.
> Add test for HTTPS backends

- Gomfile
The updated version includes fixes for a couple of file descriptor
leaks. It also makes it abort a reload if the new server fails to start.
https://github.com/alext/tablecloth/compare/b373a9a...fbddb1a
> Bump tablecloth version.

- Gomfile
The build is currently failing on master because it can't find quantile
(a dependency of vegeta). I'm not sure why this was working before, and
has stopped now, but we should be pinning this anyway.
This should fix build failures like https://ci-new.alphagov.co.uk/job/govuk_router/114/console
> Fix dependency installation.

- README.md
- integration_tests/redirect_test.go
- integration_tests/route_selection_test.go
- router.go
The database contains these special routes in their %-encoded form, but
the paths we were comparing against were in their decoded form, and
therefore didn't match. This updates our matching code to decode the
paths from the database before comparing against the request URL so that
we're comparing equivalent forms.
This is needed to support some redirects for common typos (eg `/vehicle tax`).
/cc @jamiecobbett 
Fixes #96
> Support special characters (eg space) in paths.

- README.md
- integration_tests/disabled_routes_test.go
- router.go
This allows a route to be flagged as disabled. In this case, the router
will return a 503 for all matching requests. This is occasionally needed
if we need to take a service offline for maintenance etc.
Pivotal: https://www.pivotaltracker.com/story/show/102736052
> Add support for disabled routes

- handlers/redirect_handler.go
- integration_tests/disabled_routes_test.go
- integration_tests/error_handling_test.go
- integration_tests/gone_test.go
- integration_tests/performance_test.go
- integration_tests/proxy_function_test.go
- integration_tests/redirect_test.go
- integration_tests/reload_api_test.go
- integration_tests/route_helpers.go
- integration_tests/route_loading_test.go
- integration_tests/route_selection_test.go
- router.go
https://trello.com/c/BYS3dxxV/118-panopticon-unpublishings-should-redirect-without-keeping-subpath-medium
By default, prefix redirects preserve the path sections after the
prefix and add them to the redirect destination. This isn’t always the
desired behaviour.
This adds a new `prefix_mode` field for redirect routes, set to
`preserve` (the existing behaviour) or `ignore`. If the field isn’t
present in the route document, this will default to `preserve` for
prefix routes.
If the mode is set to `ignore`, the path sections after the prefix will
be discarded and all requests will be redirected to the exact target.
Includes test refactoring to support this work. See individual commits for details.
/cc @alext @bradwright
> Add new behaviour for prefix redirects

- integration_tests/reload_api_test.go
- integration_tests/router_support.go
- main.go
- router_api.go
Supersedes #104 
Use a channel based mechanism for actioning router reload requests from
router-api. POST requests to /reload will now result in a message being
sent to a channel which will cause a goroutine to reload the routes.
The channel has a capacity of 1 in order to handle a request arriving
while routes are being reloaded. In this situation, the message will be
“queued” in the channel ready to be read again once the reload for loop
is complete.
The response for /reload is changed to be a 202 to reflect that the
reload is no longer synchronous.
Opinions are welcome on the test case.
> Make router reloading asynchronous

- README.md
The readme file says to run `go install github.com/tools/godep` to install godep. However, running this in my development VM gave the following error message:
```
can't load package: package github.com/tools/godep: cannot find package "github.com/tools/godep" in any of:
/usr/lib/goenv/versions/1.6.3/src/github.com/tools/godep (from $GOROOT)
/var/govuk/gopath/src/github.com/tools/godep (from $GOPATH)
```
Looking at https://github.com/tools/godep/blob/master/Readme.md, the command it suggests is `go get github.com/tools/godep`, which works.
Is this simply a change in naming in newer versions of the `go` command, or am I missing something here?
> Fix command for installing godep in readme

- README.md
router needs to be checked out into the `$GOPATH` on the development VM to work correctly with `bowl` etc. This adds instructions to the README
> Add development VM instructions

- README.md
Now we've sorted the GOPATH issues in the development VM, we don't need these instructions any more.
This reverts commit ae8ff90a6a5ba55bb802b450a98565bb77bc918a.
> Remove development VM instructions

- Makefile
- README.md
Add information to the README to clarify that the router needs to be built from within a Go workspace.
Also remove an unnecessary build target.
> Update README to clarify local dev requirements

- .gitignore
- Makefile
- integration_tests/router_support.go
- jenkins.sh
Part of standardising the build process for GOV.UK Go apps, this change simplifies the `Makefile`, and adds clarification to the `jenkins.sh` file as to what's going on.
Go projects need to be built from with a Go workspace, which is a directory tree with a specific format.  The default checkout path isn't enough, so we need to create that workspace and build from within there.  This functionality was already in the `jenkins.sh` file, but this changeset better documents what's going on and why for those folks who might not be aware.
> Build process simplification and clarification

- README.md
I've just removed the application page from the tech wiki. This blog post was mentioned there and provides useful background reading.
https://trello.com/c/RfRRgVqU
> Update README with link to blog post

- Jenkinsfile
As part of the build process push the binary to S3 for easier access.
> Push the binary to s3

- Jenkinsfile
- In PR 128, changes similar to this were reverted because we didn't want to
use new release tags without consulting with developers. We newly need these
changes, as we're reverting from Router being deployed on AWS in a container,
so use the old style release tags (hence why this isn't a simple revert of a
revert).
https://trello.com/c/IbnMEmul/793-router-move-away-from-container-deployment
> Push the built Go binary to S3, so we can deploy from AWS

- Jenkinsfile
Previously just a tag of "release_${buildNumber}" was being created and
not "release" which meant this was inconsistent with github and meant
that "release" can't be deployed on CI.
> Tag a docker release image

- Jenkinsfile
As AWS deploys use an S3 artefact and integration deploys by accessing
these we need to have both a release_${buildNumber} one and a release
one.
In the commit previous to this I mistakenly thought these came from
docker tags.
> Add release artefact to S3

- Jenkinsfile
Use the govuk_jenkinslib deployIntegration function, and switch to
deploying release_... instead of release, as this means it's
possible to more easily work out what was released. The Release app
also depends on the tag being used, rather than the branch for
displaying releases against commits.
> Update how the deploy job is run

- Jenkinsfile
This will trigger a dependent build on [publishing-e2e-tests][1] when
builds are done for Router. This is because we want changes to router to
be tested amongst the context of publishing-e2e-tests since a change in
router behaviour can break these apps.
[1]: https://github.com/alphagov/publishing-e2e-tests
> Run publishing-e2e-tests when Router builds

- integration_tests/route_helpers.go
This will make it possible to configure the tests to point at a different mongo in govuk-docker (https://github.com/alphagov/govuk-docker).
https://trello.com/c/hwMoAOau
> Use environment variable for mongo in testing

- Jenkinsfile
there is no longer a push to mirror in gitlab in the jenkinslib
this has moved to concourse job elsewhere
> remove pushToGitlabMirror stage

- go.mod
- go.sum
- handlers/backend_handler.go
- handlers/backend_handler_test.go
- handlers/handlers_suite_test.go
- handlers/redirect_handler_test.go
Tests a change to router whereby if an error is thrown for a request, 
the response body is closed.
This comes off the back of a hypothesis from @tlwr on what could be
causing the increased amount of open files on the cache machines.
The increased file handles only seem to occur in production, but we have 
deployed the branch changes to staging to see if any unusual behaviour occurs
before 'testing' this in prod.
Co-authored: @bilbof 
Related incident:
https://docs.google.com/document/d/1gCCSj-WgtK0_TY19J00qf4PiNV5z0KFoLArWkPBgGAg/edit#
> Close request body on error

- Dockerfile
When updating the cert bundle in alphagov/router-api#269 I changed its
filename to the one that Amazon uses so that it's easy to find next time
it needs updating.  I didn't spot that it also appears in the Docker images.
> Fix RDS cert bundle filename in Docker image.

- Makefile
What
----
Change `make test` to use `go list`
Why
----
I interpret the intention of `make test` to:
* run all tests except the integration tests
* run the integration tests verbosely
The original "go test -race ./trie ./triemux ./handlers" command missed out on the logger package (although there are no tests in logger)
"go list ./..." recursively lists all packages in the current directory
Using go list in the make task means that if there is a refactoring, and a new package is added, or a package is renamed, the intended tests will still run
How to review
----
Review CI output resembles:
```
make test
go build -ldflags "-X main.version=release_212-1-g727af70-dirty" -o /Users/tobylornewelchrichards/Code/router/router
go test -race -count=1 $(go list ./... | grep -v integration_tests)
? …
```
> Makefile "make test" uses go list

- handlers/metrics.go
At the moment, router's metrics bucket response times into:
* Less than 250ms
* 250ms - 500ms
* 500ms - 1s
* 1s - 2s
* 2s - 4s
* 4s - 8s
* More than 8s
From looking at our metrics, the majority of our responses complete in
less than 250ms, so this is not a particularly useful distribution.
By starting the exponential buckets at 1/16 of a second instead of 1/4
we should get a much more useful view of the latency distribution.
I've added one more bucket, so we can still see the 2-4 second range.
Responses that take more than 4 seconds should just be considered as
"very slow", so losing the "more than 8 seconds" bucket isn't really a
problem.
I've been trying to visualise this histogram as a heatmap in Grafana. At the moment it looks like this:
All the interesting stuff is happening in that …
> Adjust histogram buckets for faster responses

- integration_tests/route_loading_test.go
- router.go
During the migration to ECS, Replatforming intends to run router in ECS and EC2, using the same backing database managed by Router API, hosted in EC2.
One problem with this approach is that ECS and EC2 apps are served at different domains (as below):
- https://calendars.integration.govuk-internal.digital/
- http://calendars.mesh.govuk-internal.digital/
Router looks up the entire backend_url from its database. This currently makes it impossible to run two different Router applications which serve different domains, but use the same database.
Rather than store the backend_url for a backend in Router API's database, we'll provide backend URLs as environment variables such as
```
BACKEND_URL_content-store=https://content-store.gov.uk/
BACKEND_URL_search-api=https://search.gov.uk/
```
If an …
> Enable Router to be configured with multiple domains

- Makefile
- integration_tests/router_support.go
- main.go
- router.go
- router_api.go
- router_test.go
This PR adds functionality to Router so that it takes charge of updating its own routes, polling MongoDB every 30 seconds to check for changes and performing the swapping of route tables if updates are found to have occurred. This change takes place at the same time as we stop requests being sent by Router API to force updates to Router instances, allowing us to decouple these apps and make it far easier to run in ECS (as Router API no longer needs to know where to find Router instances).
[For more information around these changes, view RFC 135](https://github.com/alphagov/govuk-rfcs/blob/main/rfc-135-updating-routes-in-router.md).
> Update routes within router

- Dockerfile
This makes the router image consistent with other GOV.UK Docker images.
If an image specifies an `ENTRYPOINT`, then the `CMD` or `COMMAND` get appended as arguments to the `ENTRYPOINT` when running the container.
For example, `docker run govuk/router /bin/sh -c exit 0` would start the router app (passing `/bin/sh ...` as an arg to `/bin/router`), rather than exiting as expected.
Entrypoint is similar to command since it specifies what executable to run when the container starts. However, entrypoint is purposefully more difficult to override.
Also, since we are bringing up Router in ECS, it would be good for this image to be similar to the others we're running. Though, [Entrypoint is supported by ECS](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/task_definition_parameters.htm …
> Use cmd, not entrypoint, in docker image

- integration_tests/performance_test.go
- integration_tests/reload_api_test.go
- router.go
- router_test.go
- triemux/mux.go
- triemux/mux_test.go
This essentially reverts #56.
AFAICT the checksum is not used anywhere (even in monitoring), but it recently started causing a real problem because it's asking MongoDB to sort the routes collection.  Apart from being inefficient, this runs into a scaling limitation of Mongo and led to route reloads failing under certain circumstances with errors like `Runner error during find: Overflow sort stage buffered data usage of 33554700 bytes exceeds internal limit of 33554432 bytes`.
We could alternatively add indices on those fields, but it's much better to remove the disused feature. This way we reduce the maintenance burden and maybe improve scalability a bit by eliminating unnecessary work on reloads.
Tested: Ran the testsuite locally:
```
$ make test_with_docker
...
Ran 103 of 106 Specs in …
```
> Remove disused checksum feature

- handlers/metrics.go
- handlers/redirect_handler.go
- handlers/redirect_handler_test.go
This was OOMing Prometheus in prod and using taking up most of the long-term storage.
The fix is not to try to include the redirect URL as a label. Prometheus isn't designed for such high-cardinality metrics.
Tested: `Ran 103 of 106 Specs in 59.253 seconds` `SUCCESS! -- 103 Passed | 0 Failed | 2 Pending | 1 Skipped`
> Fix cardinality of router_redirect_handler_redirect_total metric.

- .github/workflows/ci.yaml
After some discussion within the team, we have decided that its not necessary to have Github actions CI run on PR's for now.
What should happen on PR's is something we will visit again at a later date.
> Remove GitHub actions Publish to ECR on a pull request.

- README.md
Add information on how to update the version of Go that router is running.
Rendered [Readme](https://github.com/alphagov/router/blob/dc34bfc499914d26f01ebdc83c9617b06f1ab6bb/README.md#updating-the-version-of-go)
> Update docs with information on bumping Go version

- main.go
We're overriding this from 15s to 20s in all environments, so let's just set the default to the value we want and save a bit of noise in configuration files.
See https://github.com/alphagov/govuk-puppet/blob/main/modules/govuk/manifests/apps/router.pp#L59
> Set the default header timeout to what we're actually using everywhere.

- README.md
Adds some useful information from https://github.com/alphagov/govuk-puppet/pull/11579 so that it's not lost
in the sands of time.
> Update documentation on Go upgrades

- .github/workflows/ci.yaml
GoLang is updated in the Rakefile by Dependabot but it doesn't touch the CI file, which also needs to know the correct version. This is updated here to bring it up to parity with the Rakefile version.
Until this has been merged and Puppet run: https://github.com/alphagov/govuk-puppet/pull/11859
Related to: https://trello.com/c/lIF8IVxq/1392-bug-investigate-broken-router-builds
> Ensure GoLang version is correct in CI framework

- Jenkinsfile
We're decommissioning the [Publishing E2E tests][] now that GOV.UK apps have transitioned to a model of continuous deployment with contract tests, as outlined in [RFC-128][]. The overall progress of this work is tracked in a [Trello card on the GOV.UK Tech Debt board][tech-debt-card].
[Publishing E2E tests]: https://github.com/alphagov/publishing-e2e-tests
[RFC-128]: https://github.com/alphagov/govuk-rfcs/blob/main/rfc-128-continuous-deployment.md#delete-publishing-e2e-tests
[tech-debt-card]: https://trello.com/c/Lbw4TTfD/233-publishing-e2e-tests-still-exist
This PR removes the E2E tests from this app's CI pipeline. Once merged, the Jenkins CI server will no longer kick off a run of the publishing-e2e-tests job when new PRs are opened.
This change is the first step in the overall …
> Remove Publishing E2E tests from Jenkinsfile

- Jenkinsfile
Trello: https://trello.com/c/amnaU0V9/853-decommission-the-publishing-end-to-end-tests
The images produced by this were only used by the publishing-e2e-tests
suite, now that this has been retired [1] we no longer need these
actions and intend to remove them from govuk-jenkinslib.
[1]: https://github.com/alphagov/govuk-jenkinslib/pull/120
This also replaces a deprecated function.
> Remove Jenkins Docker build tasks 

- README.md
The instructions missed a couple of crucial steps and left ambiguity in what to do in certain scenarios. This commit addresses this by adding both a missing step in the upgrade process and a guide on manually upgrading Go modules when required.
> Add further instructions for upgrading GoLang in Router

- .dockerignore
- Dockerfile
Improvements to reduce attack surface, image size, build time/resources and readability of the Dockerfile.
- Speed up the build by using `golang:alpine` as the builder image.
- Add some directories to `.dockerignore` to avoid unnecessary copying during build.
- Include only the Go binary in the output image. For casual troubleshooting we can shell into the `nginx` container and for anything fancy we'd use a rescue container anyway (such as [`kubespy`](https://github.com/huazhihao/kubespy) or similar).
- Strip debug info from the Go binary. This does not break stacktraces.
- Specify `-trimpath` so we don't include the building user's filesystem paths (e.g. `/home/sengi/src/alphagov/router/...`) in the Go binary.
- Respect `TARGETARCH` and `TARGETOS` for cross-compilation.
- Run as an …
> Improve container image build.

- Dockerfile
Router needs this for the TLS connection to the Licensify backend.
> Include CA certs in the image.

- .github/workflows/ci.yml
Previously it was simply named "test" which wasn't ideal for moving to EKS. This renaming allows us to properly reference it in the github actions setup over in govuk-saas-config.
> Rename test to be more descriptive

- integration_tests/performance_test.go
As of Go 1.19, the `os` package [sets `RLIMIT_NOFILE`](https://cs.opensource.google/go/go/+/go1.19.9:src/syscall/rlimit.go) to the maximum available on init, so we don't even need to call `os.Setrlimit()` ourselves to enable these tests.
> Don't skip the high-concurrency tests.

- integration_tests/metrics_test.go
- integration_tests/performance_test.go
- metrics.go
- Delete some cruft from the metrics integration tests. All it was really doing was looking for a plausible 200 OK response for `/metrics`, so make it explicitly just do that and don't pretend to test the actual metrics. We should add proper unit tests (not integration tests) to check that counters are incremented when they're supposed to be (see [prometheus/testutil](https://pkg.go.dev/github.com/prometheus/client_golang/prometheus/testutil)).
- Refactor the performance tests and make them generate a realistic request rate (50 qps for most tests and 500 qps for the high-throughput ones, instead of 1.7 qps and 50 qps respectively).
> More test improvements.

- README.md
- fix broken heading
- [house style](https://www.gov.uk/guidance/style-guide/a-to-z-of-gov-uk-style#bullet-points-steps)
- simplify wording
> Fix formatting and style in README.

- handlers/redirect_handler_test.go
This table-driven test was full of branches and was testing a whole bunch of different behaviours.
- Split it into separate tests that test one thing each.
- Stop doing exact comparisons on floating point numbers.
- Clean up the other few tests in the module.
- Use table-driven tests where appropriate.
> Refactor table-driven test that was doing too much.

- lib/metrics.go
- lib/router.go
I'm super curious about how long these take, as we're loading around 1M routes from the database every time the routes reload (over 1M in draft, just under in live). Al reckons about 20s, based on the logs, but it would be good to know for sure.
This adds a summary metric to which will allow us to calculate median / 90th / 95th / 99th percentile durations.
I've also added labels to the count / duration metrics so we can tell which ones are successes and failures. If you don't put success / failure labels on your duration metrics they can get all mucked up by quick failures and slow successes, which you can't distinguish between.
Prometheus summaries / histograms[0] are a bit hard to wrap one's head around, but I think summary is the right choice here. Key factors:
1) With Histograms, you …
> Add a summary metric for route reload durations

- README.md
One example of running the tests with debug logging suffices. Keep the more portable of the two.
Slightly improves the signal/noise ratio, especially since this is the top-level README.
> Remove an esoteric example from the README.

- README.md
- trie/README.md
- triemux/README.md
Platform Engineering now maintains Router (and [Router API](https://github.com/alphagov/router-api)). Update the top-level README to reflect this and help make it discoverable.
Also update some links and run mdformat while we're updating READMEs.
> Update README to reflect change of maintainer.

- LICENCE
- trie/LICENSE
- trie/README.md
- trie/trie.go
- trie/trie_test.go
- triemux/LICENSE
- triemux/mux.go
- triemux/mux_test.go
- Use generics (introduced in Go 1.18) to ensure type safety at compile time instead of using type introspection (type assertions) at runtime.
- Drop the unused `prefix` flag in the trie node objects; just point directly to the http.Handler (interface). Improves readability and saves an unnecessary indirection on every lookup.
- Make the clever table-driven unit tests a bit more readable by using more common terminology.
- Unexport some symbols which shouldn't have been exported (and thankfully hadn't been used externally, at least not in any public repos anyway).
- Minor editorial improvements to documentation.
- Update the copyright assertions to keep them accurate.
> Simplify the route data structures.

- mongo.sh
The antique version running in prod is apparently 2.6.12, not 2.4.
> Run tests against mongodb-2.6 instead of 2.4.

- handlers/redirect_handler.go
- integration_tests/proxy_function_test.go
- integration_tests/redirect_test.go
- triemux/mux.go
- triemux/mux_test.go
Move this redirect functionality from nginx into Router, so that we can finally drop Perl from the nginx config.
We'll need to push this further down into the backend ("frontend") apps when we get rid of Router, but there's still value in eliminating Perl from the request path sooner rather than later.
Also some trivial style cleanup in proxy_function integration tests.
> Redirect all-caps article slugs to lowercase.

- handlers/backend_handler.go
Seems the semantics of gosec's exclusion comments subtly changed recently :/ Moving the comment inside the block / directly above the statement it applies to seems to fix it.
> Move gosec annotation so that it continues to work.

- mongo.sh
This seems to have become flaky recently (but only on GitHub Actions), so try waiting a bit longer for MongoDB startup.
Might improve #433. If not then we can dig deeper.
> Increase timeout for Mongo setup in tests.

- triemux/mux.go
This change makes shouldRedirToLowercase more efficient by at start-up time compiling the regular expression that shouldRedirToLowercase uses instead of compiling and discarding it each time on a hit, with an exhibit below of the performance improvement:
```shell
$ benchstat before.txt after.txt
name                             old time/op    new time/op    delta
ShouldRedirectToLowercasePath-8    29.8µs ± 1%     0.8µs ±24%   -97.15%  (p=0.000 n=8+10)
name                             old alloc/op   new alloc/op   delta
ShouldRedirectToLowercasePath-8    33.7kB ± 0%     0.0kB       -100.00%  (p=0.000 n=9+10)
name                             old allocs/op  new allocs/op  delta
ShouldRedirectToLowercasePath-8       360 ± 0%         0       -100.00%  (p=0.000 n=10+10)
```
Fixes #444
> triemux: make shouldRedirToLowercase more efficient by regex compilation+reuse

- .github/workflows/ci.yml
The benefits of this being automatically up to date outweigh the (tiny and largely theoretical) drawback of new lints appearing unexpectedly (which we'd likely want to fix anyway).
> Toil reduction: use current golangci-lint version.

- .github/workflows/deploy.yml
- Dockerfile
This switches router over to the multi-arch build workflow and adds the `--platform` flag to the Dockerfile.
> Get multi-arch builds for Router.

- Dockerfile
At the very least, dockerls doesn't like that syntax.
> Avoid ambiguous `ARG x y` syntax in Dockerfile.

- Dockerfile
We're not using these and we're unlikely to any time soon. It's also easy to add them back in if we did want them later.
> Remove unused RDS CA cert bundles.

- integration_tests/error_handling_test.go
- integration_tests/proxy_function_test.go
- logger/logger.go
I can't find any evidence of this ever having been used, and it gives incorrect results because it throws away all but one of the [X-Varnish headers](https://developer.fastly.com/reference/http/http-headers/X-Varnish/). Any request that's reached Router would have [at least two of them](https://developer.fastly.com/learning/vcl/using/#the-vcl-request-lifecycle).
It probably made sense back when we ran our own Varnish and before we had Fastly, when these IDs would have corresponded to request log lines in Varnish.
> Stop logging varnish_id.

- logger/sentry.go
- main.go
We're still quite some way from using the Sentry API as intended, but this at least makes our usage a bit less weird/buggy and more readable.
- Send events to Sentry asynchronously, instead of blocking.
- Allow up to 2 s to finish sending events to Sentry on exit.
- Manage the lifecycle of the sentry.Client, Hub and Scope objects the way we're supposed to, rather than reinitialising Sentry every time we send an event.
- Remove the unexported methods on our (still somewhat sketchy) ReportableError type; these weren't helping readability.
Relevant docs:
- https://docs.sentry.io/platforms/go/usage/
- https://docs.sentry.io/platforms/go/enriching-events/scopes/
- https://docs.sentry.io/platforms/go/concurrency/
- https://docs.sentry.io/platforms/go/panics/
- …
> Lightly clean up Sentry event logging.

- docs/data-structure.md
- handlers/metrics.go
- handlers/redirect_handler.go
- handlers/redirect_handler_test.go
- integration_tests/redirect_test.go
- integration_tests/route_helpers.go
- lib/router.go
This feature isn't currently used by the publishing system, so removing to simplify code. There are only 6 old routes in the existing database have redirect_type of "temporary", this change will cause them to redirect with 301 instead.
> Remove temporary redirection

- mongo.sh
Tests frequently timeout and fail whilst waiting for MongoDB to startup. This increases the timeout to reduce the flakey-ness of these tests.
> Increase the mongo startup timeout for tests

- integration_tests/backend_helpers.go
- integration_tests/integration_test.go
- integration_tests/performance_test.go
- integration_tests/proxy_function_test.go
- integration_tests/redirect_test.go
- integration_tests/route_helpers.go
- integration_tests/route_loading_test.go
- integration_tests/route_selection_test.go
- lib/backends.go
- lib/backends_test.go
- lib/router.go
As we only have a small number of backends that change infrequently, their URL configuration can be handled by environment variables. This allows us to remove a dependency from using the Mongo Database to fetch this information and allows us to using the Content Store for route information.
Router will use any environment variable with the prefix "BACKEND_URL_", where the key suffix is the backend id and the value is the URL.
> Load backends from env vars

- lib/router.go
This allows the function be used not exclusively with the Route type. This is to support work to make Router reload routes from the Content Store.
> Change shouldPreserveSegements arguments to accept strings

- lib/load_routes.go
- lib/router.go
Currently, it reloads every minute regardless if a reload has occurred within that minute. This is because we never set the last reload time. This also improves the responsiveness by checking for a periodic reload every 5 seconds, instead of a minute (which could potentially mean a reload could take up to 2 minutes).
Renamed csLastReloadTime to csLastAttemptReloadTime for clarity.
Tested in integration
> Improve periodic reload

- .golangci.yml
- Dockerfile
- go.mod
* golangci-lint was giving a warning telling us to use usetesting linter instead of tenv, so make that change
* Update go version in Dockerfile and go.mod (using `go mod edit -go=1.24.4` and then `go mod tidy`)
* I ran the tests which passed, but seem a little flaky (even on main)
> Update go version

- integration_tests/backend_helpers.go
- integration_tests/http_request_helpers.go
- integration_tests/router_support.go
Since golangci-lint updated to 2.3 we are getting lint errors, including on main
Where we are using non-context versions of net.Listen, net.Dial, and exec.Command
This PR uses the versions of these functions which take a context, and sets it appropriately depending on the real context.
All of these are in tests, so if the tests pass this should be good to go.
See [this github actions lint failure](https://github.com/alphagov/router/actions/runs/16884080982/job/47827149450):
```
run golangci-lint
Running [/home/runner/golangci-lint-2.3.1-linux-amd64/golangci-lint config path] in [/home/runner/work/router/router] ...
Running [/home/runner/golangci-lint-2.3.1-linux-amd64/golangci-lint config verify] in [/home/runner/work/router/router] ...
Running …
```
> Resolve lint errors for functions without contexts
